// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ninjaTax.Data;

#nullable disable

namespace ninjaTax.Migrations.Sqlite
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926153808_AddPurchaseAndSalesModules")]
    partial class AddPurchaseAndSalesModules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ninjaTax.Models.Entities.ButToan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DienGiai")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayChungTu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayChungTuGoc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayHachToan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoChungTu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoChungTuGoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongCo")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongNo")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SoChungTu")
                        .IsUnique();

                    b.ToTable("ButToan", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietButToan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ButToanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DienGiai")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DoiTuongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DongSo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("TaiKhoanCoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaiKhoanNoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ButToanId");

                    b.HasIndex("DoiTuongId");

                    b.HasIndex("TaiKhoanCoId");

                    b.HasIndex("TaiKhoanNoId");

                    b.ToTable("ChiTietButToan", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietHoaDonBan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DonGiaVon")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("DongSo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HoaDonBanHangId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("TaiKhoanDoanhThuId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TaiKhoanGiaVonId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TaiKhoanKhoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaiKhoanNoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaiKhoanThueId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThueSuatVat")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TiLeChietKhau")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienChietKhau")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienThueVat")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("VatTuHangHoaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonBanHangId");

                    b.HasIndex("TaiKhoanDoanhThuId");

                    b.HasIndex("TaiKhoanGiaVonId");

                    b.HasIndex("TaiKhoanKhoId");

                    b.HasIndex("TaiKhoanNoId");

                    b.HasIndex("TaiKhoanThueId");

                    b.HasIndex("VatTuHangHoaId");

                    b.ToTable("ChiTietHoaDonBan", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietHoaDonMua", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("DongSo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HoaDonMuaHangId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("TaiKhoanCoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaiKhoanNoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaiKhoanThueId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThueSuatVat")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TiLeChietKhau")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienChietKhau")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienThueVat")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("VatTuHangHoaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonMuaHangId");

                    b.HasIndex("TaiKhoanCoId");

                    b.HasIndex("TaiKhoanNoId");

                    b.HasIndex("TaiKhoanThueId");

                    b.HasIndex("VatTuHangHoaId");

                    b.ToTable("ChiTietHoaDonMua", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.DoiTruCongNo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ButToanId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DoiTuongId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HoaDonBanHangId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HoaDonMuaHangId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Loai")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayDoiTru")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoTienDoiTru")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ButToanId");

                    b.HasIndex("DoiTuongId");

                    b.HasIndex("HoaDonBanHangId");

                    b.HasIndex("HoaDonMuaHangId");

                    b.ToTable("DoiTruCongNo", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.DoiTuong", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Loai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaDoiTuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiLienHe")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoTaiKhoanNganHang")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDoiTuong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNganHang")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaDoiTuong")
                        .IsUnique();

                    b.ToTable("DoiTuong", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.HoaDonBanHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BanHangKiemXuatKho")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ButToanDoanhThuId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ButToanGiaVonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChuKySo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DaThuTien")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChiKH")
                        .HasColumnType("TEXT");

                    b.Property<string>("DienGiai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HanThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<string>("KHMauSo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("KhachHangId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KyHieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaCoQuanThue")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSoThueKH")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayChungTu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayHachToan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayHoaDon")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoChungTu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhachHang")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongThanhToan")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTienChietKhau")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTienHang")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTienThueVat")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ButToanDoanhThuId");

                    b.HasIndex("ButToanGiaVonId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("SoChungTu")
                        .IsUnique();

                    b.ToTable("HoaDonBanHang", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.HoaDonMuaHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ButToanId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DaThanhToan")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChiNCC")
                        .HasColumnType("TEXT");

                    b.Property<string>("DienGiai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HanThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<string>("KHMauSoHoaDon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("KyHieuHoaDon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSoThueNCC")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaTraCuuHdt")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MuaHangKiemKho")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayChungTu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayHachToan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayHoaDon")
                        .HasColumnType("TEXT");

                    b.Property<long>("NhaCungCapId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoChungTu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNCC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongThanhToan")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTienChietKhau")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTienHang")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTienThueVat")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ButToanId");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("SoChungTu")
                        .IsUnique();

                    b.ToTable("HoaDonMuaHang", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacTaiKhoan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LaTaiKhoanSoCai")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoaiTaiKhoan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TaiKhoanMeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("TinhChat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.HasIndex("TaiKhoanMeId");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.VatTuHangHoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangTheoDoiTonKho")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGiaBanTieuChuan")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DonGiaMuaGanNhat")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LoaiVatTu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaVatTu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TaiKhoanDoanhThuId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TaiKhoanGiaVonId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TaiKhoanKhoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenVatTu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThueSuatVatMacDinh")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaVatTu")
                        .IsUnique();

                    b.HasIndex("TaiKhoanDoanhThuId");

                    b.HasIndex("TaiKhoanGiaVonId");

                    b.HasIndex("TaiKhoanKhoId");

                    b.ToTable("VatTuHangHoa", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietButToan", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToan")
                        .WithMany("ChiTietButToans")
                        .HasForeignKey("ButToanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.DoiTuong", "DoiTuong")
                        .WithMany()
                        .HasForeignKey("DoiTuongId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanCo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanCoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanNo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanNoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ButToan");

                    b.Navigation("DoiTuong");

                    b.Navigation("TaiKhoanCo");

                    b.Navigation("TaiKhoanNo");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietHoaDonBan", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.HoaDonBanHang", "HoaDonBanHang")
                        .WithMany("ChiTietBans")
                        .HasForeignKey("HoaDonBanHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanDoanhThu")
                        .WithMany()
                        .HasForeignKey("TaiKhoanDoanhThuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanGiaVon")
                        .WithMany()
                        .HasForeignKey("TaiKhoanGiaVonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanKho")
                        .WithMany()
                        .HasForeignKey("TaiKhoanKhoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanNo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanNoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanThue")
                        .WithMany()
                        .HasForeignKey("TaiKhoanThueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.VatTuHangHoa", "VatTuHangHoa")
                        .WithMany()
                        .HasForeignKey("VatTuHangHoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDonBanHang");

                    b.Navigation("TaiKhoanDoanhThu");

                    b.Navigation("TaiKhoanGiaVon");

                    b.Navigation("TaiKhoanKho");

                    b.Navigation("TaiKhoanNo");

                    b.Navigation("TaiKhoanThue");

                    b.Navigation("VatTuHangHoa");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietHoaDonMua", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.HoaDonMuaHang", "HoaDonMuaHang")
                        .WithMany("ChiTietHangs")
                        .HasForeignKey("HoaDonMuaHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanCo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanCoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanNo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanNoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanThue")
                        .WithMany()
                        .HasForeignKey("TaiKhoanThueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.VatTuHangHoa", "VatTuHangHoa")
                        .WithMany()
                        .HasForeignKey("VatTuHangHoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDonMuaHang");

                    b.Navigation("TaiKhoanCo");

                    b.Navigation("TaiKhoanNo");

                    b.Navigation("TaiKhoanThue");

                    b.Navigation("VatTuHangHoa");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.DoiTruCongNo", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToan")
                        .WithMany()
                        .HasForeignKey("ButToanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.DoiTuong", "DoiTuong")
                        .WithMany()
                        .HasForeignKey("DoiTuongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.HoaDonBanHang", "HoaDonBanHang")
                        .WithMany()
                        .HasForeignKey("HoaDonBanHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.HoaDonMuaHang", "HoaDonMuaHang")
                        .WithMany()
                        .HasForeignKey("HoaDonMuaHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ButToan");

                    b.Navigation("DoiTuong");

                    b.Navigation("HoaDonBanHang");

                    b.Navigation("HoaDonMuaHang");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.HoaDonBanHang", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToanDoanhThu")
                        .WithMany()
                        .HasForeignKey("ButToanDoanhThuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToanGiaVon")
                        .WithMany()
                        .HasForeignKey("ButToanGiaVonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ninjaTax.Models.Entities.DoiTuong", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ButToanDoanhThu");

                    b.Navigation("ButToanGiaVon");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.HoaDonMuaHang", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToan")
                        .WithMany()
                        .HasForeignKey("ButToanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ninjaTax.Models.Entities.DoiTuong", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ButToan");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.TaiKhoan", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanMe")
                        .WithMany("TaiKhoanCons")
                        .HasForeignKey("TaiKhoanMeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoanMe");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.VatTuHangHoa", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanDoanhThu")
                        .WithMany()
                        .HasForeignKey("TaiKhoanDoanhThuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanGiaVon")
                        .WithMany()
                        .HasForeignKey("TaiKhoanGiaVonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanKho")
                        .WithMany()
                        .HasForeignKey("TaiKhoanKhoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoanDoanhThu");

                    b.Navigation("TaiKhoanGiaVon");

                    b.Navigation("TaiKhoanKho");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ButToan", b =>
                {
                    b.Navigation("ChiTietButToans");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.HoaDonBanHang", b =>
                {
                    b.Navigation("ChiTietBans");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.HoaDonMuaHang", b =>
                {
                    b.Navigation("ChiTietHangs");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("TaiKhoanCons");
                });
#pragma warning restore 612, 618
        }
    }
}
