// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ninjaTax.Data;

#nullable disable

namespace ninjaTax.Migrations.Sqlite
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926234034_AddPayrollAndTaxModules")]
    partial class AddPayrollAndTaxModules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ninjaTax.Models.Entities.BangChamCongThang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("KyKeToan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nam")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoNgayCongChuan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Thang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KyKeToan")
                        .IsUnique();

                    b.ToTable("BangChamCongThang", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.BangLuongThang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ButToanBaoHiemDnId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ButToanChiPhiLuongId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ButToanKhauTruLuongId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KyKeToan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayGhiSo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoChungTu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoNgayCongChuan")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TongBaoHiemDnGanh")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongBaoHiemNldGanh")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongQuyLuong")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongThucLinh")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongThueTncn")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ButToanBaoHiemDnId");

                    b.HasIndex("ButToanChiPhiLuongId");

                    b.HasIndex("ButToanKhauTruLuongId");

                    b.HasIndex("KyKeToan")
                        .IsUnique();

                    b.HasIndex("SoChungTu")
                        .IsUnique();

                    b.ToTable("BangLuongThang", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.BangTinhKhauHao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ButToanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaTriConLai")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("KyKeToan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LuyKeKhauHao")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NguyenGia")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoTienKhauHao")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("TaiSanCoDinhId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ButToanId");

                    b.HasIndex("TaiSanCoDinhId", "KyKeToan")
                        .IsUnique();

                    b.ToTable("BangTinhKhauHao", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ButToan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DienGiai")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayChungTu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayChungTuGoc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayHachToan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoChungTu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoChungTuGoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongCo")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongNo")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SoChungTu")
                        .IsUnique();

                    b.ToTable("ButToan", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietButToan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ButToanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DienGiai")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DoiTuongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DongSo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("TaiKhoanCoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaiKhoanNoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ButToanId");

                    b.HasIndex("DoiTuongId");

                    b.HasIndex("TaiKhoanCoId");

                    b.HasIndex("TaiKhoanNoId");

                    b.ToTable("ChiTietButToan", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietChamCong", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BangChamCongThangId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GioLamThemNgayLe")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GioLamThemNgayNghi")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GioLamThemNgayThuong")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("NhanVienId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SoNgayDiLam")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoNgayNghiKhongLuong")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoNgayNghiLe")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoNgayNghiOmBhxh")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoNgayNghiPhep")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoNgayNghiThaiSan")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongCongTinhLuong")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.HasIndex("BangChamCongThangId", "NhanVienId")
                        .IsUnique();

                    b.ToTable("ChiTietChamCong", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietChungTuThuChi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChungTuThuChiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DienGiai")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DoiTuongId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("TaiKhoanCoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaiKhoanNoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChungTuThuChiId");

                    b.HasIndex("DoiTuongId");

                    b.HasIndex("TaiKhoanCoId");

                    b.HasIndex("TaiKhoanNoId");

                    b.ToTable("ChiTietChungTuThuChi", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietHoaDonBan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DonGiaVon")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("DongSo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HoaDonBanHangId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("TaiKhoanDoanhThuId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TaiKhoanGiaVonId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TaiKhoanKhoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaiKhoanNoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaiKhoanThueId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThueSuatVat")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TiLeChietKhau")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienChietKhau")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienThueVat")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("VatTuHangHoaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonBanHangId");

                    b.HasIndex("TaiKhoanDoanhThuId");

                    b.HasIndex("TaiKhoanGiaVonId");

                    b.HasIndex("TaiKhoanKhoId");

                    b.HasIndex("TaiKhoanNoId");

                    b.HasIndex("TaiKhoanThueId");

                    b.HasIndex("VatTuHangHoaId");

                    b.ToTable("ChiTietHoaDonBan", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietHoaDonMua", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("DongSo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HoaDonMuaHangId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("TaiKhoanCoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaiKhoanNoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaiKhoanThueId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThueSuatVat")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TiLeChietKhau")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienChietKhau")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienThueVat")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("VatTuHangHoaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonMuaHangId");

                    b.HasIndex("TaiKhoanCoId");

                    b.HasIndex("TaiKhoanNoId");

                    b.HasIndex("TaiKhoanThueId");

                    b.HasIndex("VatTuHangHoaId");

                    b.ToTable("ChiTietHoaDonMua", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietLuongNhanVien", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BangLuongThangId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BhtnDn")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BhtnNld")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BhxhDn")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BhxhNld")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BhytDn")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BhytNld")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiamTruBanThan")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiamTruNguoiPhuThuoc")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KpcdDn")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LuongDongBaoHiem")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LuongLamThemGio")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LuongOtMienThue")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LuongThoiGian")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("NhanVienId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PhuCapChiuThue")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PhuCapMienThue")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TamUng")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThuNhapTinhThue")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThucLinh")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThueTncnKhauTru")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienThuong")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongBaoHiemDn")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongBaoHiemNld")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongThuNhap")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.HasIndex("BangLuongThangId", "NhanVienId")
                        .IsUnique();

                    b.ToTable("ChiTietLuongNhanVien", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChungTuThuChi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ButToanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DoiTuongId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HoaDonBanHangId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HoaDonMuaHangId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoaiChungTu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LyDo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayChungTu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayHachToan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiGiaoNopNhan")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoChungTu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoChungTuGoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TaiKhoanNganHangId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ViPhamQuyTac20Tr")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ButToanId");

                    b.HasIndex("DoiTuongId");

                    b.HasIndex("HoaDonBanHangId");

                    b.HasIndex("HoaDonMuaHangId");

                    b.HasIndex("SoChungTu")
                        .IsUnique();

                    b.HasIndex("TaiKhoanNganHangId");

                    b.ToTable("ChungTuThuChi", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.DoiTruCongNo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ButToanId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DoiTuongId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HoaDonBanHangId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HoaDonMuaHangId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Loai")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayDoiTru")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoTienDoiTru")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ButToanId");

                    b.HasIndex("DoiTuongId");

                    b.HasIndex("HoaDonBanHangId");

                    b.HasIndex("HoaDonMuaHangId");

                    b.ToTable("DoiTruCongNo", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.DoiTuong", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Loai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaDoiTuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiLienHe")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoTaiKhoanNganHang")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDoiTuong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNganHang")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaDoiTuong")
                        .IsUnique();

                    b.ToTable("DoiTuong", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.HoaDonBanHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BanHangKiemXuatKho")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ButToanDoanhThuId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ButToanGiaVonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChuKySo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DaThuTien")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChiKH")
                        .HasColumnType("TEXT");

                    b.Property<string>("DienGiai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HanThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<string>("KHMauSo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("KhachHangId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KyHieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaCoQuanThue")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSoThueKH")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayChungTu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayHachToan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayHoaDon")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoChungTu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhachHang")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongThanhToan")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTienChietKhau")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTienHang")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTienThueVat")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ButToanDoanhThuId");

                    b.HasIndex("ButToanGiaVonId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("SoChungTu")
                        .IsUnique();

                    b.ToTable("HoaDonBanHang", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.HoaDonMuaHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ButToanId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DaThanhToan")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChiNCC")
                        .HasColumnType("TEXT");

                    b.Property<string>("DienGiai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HanThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<string>("KHMauSoHoaDon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("KyHieuHoaDon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSoThueNCC")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaTraCuuHdt")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MuaHangKiemKho")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayChungTu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayHachToan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayHoaDon")
                        .HasColumnType("TEXT");

                    b.Property<long>("NhaCungCapId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoChungTu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNCC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongThanhToan")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTienChietKhau")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTienHang")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTienThueVat")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ButToanId");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("SoChungTu")
                        .IsUnique();

                    b.ToTable("HoaDonMuaHang", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.NhanVien", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CoCamKet08")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangLamViec")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DongBaoHiem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LaDoanVienCongDoan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoaiHopDong")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LuongCoBan")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LuongDongBaoHiem")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayKetThucHd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhongBan")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PhuCapAnTrua")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PhuCapDienThoai")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PhuCapTrachNhiem")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PhuCapTrangPhuc")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoCccd")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoNguoiPhuThuoc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoSoBhxh")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoTaiKhoanNganHang")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacTaiKhoan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LaTaiKhoanSoCai")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoaiTaiKhoan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TaiKhoanMeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("TinhChat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.HasIndex("TaiKhoanMeId");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.TaiKhoanNganHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChiNhanh")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChuTaiKhoan")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoDuBanDau")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TaiKhoanKeToanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenNganHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SoTaiKhoan")
                        .IsUnique();

                    b.HasIndex("TaiKhoanKeToanId");

                    b.ToTable("TaiKhoanNganHang", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.TaiSanCoDinh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoPhanSuDung")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaTriConLai")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaTriDaKhauHao")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("LoaiTaiSan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaTaiSan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MucKhauHaoThang")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayBatDauKhauHao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayGhiTang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NguyenGia")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("TaiKhoanChiPhiId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TaiKhoanKhauHaoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaiKhoanNguyenGiaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenTaiSan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ThoiGianSuDungThang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaTaiSan")
                        .IsUnique();

                    b.HasIndex("TaiKhoanChiPhiId");

                    b.HasIndex("TaiKhoanKhauHaoId");

                    b.HasIndex("TaiKhoanNguyenGiaId");

                    b.ToTable("TaiSanCoDinh", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.VatTuHangHoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangTheoDoiTonKho")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGiaBanTieuChuan")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DonGiaMuaGanNhat")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LoaiVatTu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaVatTu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TaiKhoanDoanhThuId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TaiKhoanGiaVonId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TaiKhoanKhoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenVatTu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThueSuatVatMacDinh")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaVatTu")
                        .IsUnique();

                    b.HasIndex("TaiKhoanDoanhThuId");

                    b.HasIndex("TaiKhoanGiaVonId");

                    b.HasIndex("TaiKhoanKhoId");

                    b.ToTable("VatTuHangHoa", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.BangLuongThang", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToanBaoHiemDn")
                        .WithMany()
                        .HasForeignKey("ButToanBaoHiemDnId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToanChiPhiLuong")
                        .WithMany()
                        .HasForeignKey("ButToanChiPhiLuongId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToanKhauTruLuong")
                        .WithMany()
                        .HasForeignKey("ButToanKhauTruLuongId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ButToanBaoHiemDn");

                    b.Navigation("ButToanChiPhiLuong");

                    b.Navigation("ButToanKhauTruLuong");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.BangTinhKhauHao", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToan")
                        .WithMany()
                        .HasForeignKey("ButToanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ninjaTax.Models.Entities.TaiSanCoDinh", "TaiSanCoDinh")
                        .WithMany("BangTinhKhauHaos")
                        .HasForeignKey("TaiSanCoDinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ButToan");

                    b.Navigation("TaiSanCoDinh");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietButToan", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToan")
                        .WithMany("ChiTietButToans")
                        .HasForeignKey("ButToanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.DoiTuong", "DoiTuong")
                        .WithMany()
                        .HasForeignKey("DoiTuongId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanCo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanCoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanNo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanNoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ButToan");

                    b.Navigation("DoiTuong");

                    b.Navigation("TaiKhoanCo");

                    b.Navigation("TaiKhoanNo");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietChamCong", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.BangChamCongThang", "BangChamCongThang")
                        .WithMany("ChiTiets")
                        .HasForeignKey("BangChamCongThangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BangChamCongThang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietChungTuThuChi", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.ChungTuThuChi", "ChungTuThuChi")
                        .WithMany("ChiTietThuChis")
                        .HasForeignKey("ChungTuThuChiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.DoiTuong", "DoiTuong")
                        .WithMany()
                        .HasForeignKey("DoiTuongId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanCo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanCoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanNo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanNoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChungTuThuChi");

                    b.Navigation("DoiTuong");

                    b.Navigation("TaiKhoanCo");

                    b.Navigation("TaiKhoanNo");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietHoaDonBan", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.HoaDonBanHang", "HoaDonBanHang")
                        .WithMany("ChiTietBans")
                        .HasForeignKey("HoaDonBanHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanDoanhThu")
                        .WithMany()
                        .HasForeignKey("TaiKhoanDoanhThuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanGiaVon")
                        .WithMany()
                        .HasForeignKey("TaiKhoanGiaVonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanKho")
                        .WithMany()
                        .HasForeignKey("TaiKhoanKhoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanNo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanNoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanThue")
                        .WithMany()
                        .HasForeignKey("TaiKhoanThueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.VatTuHangHoa", "VatTuHangHoa")
                        .WithMany()
                        .HasForeignKey("VatTuHangHoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDonBanHang");

                    b.Navigation("TaiKhoanDoanhThu");

                    b.Navigation("TaiKhoanGiaVon");

                    b.Navigation("TaiKhoanKho");

                    b.Navigation("TaiKhoanNo");

                    b.Navigation("TaiKhoanThue");

                    b.Navigation("VatTuHangHoa");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietHoaDonMua", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.HoaDonMuaHang", "HoaDonMuaHang")
                        .WithMany("ChiTietHangs")
                        .HasForeignKey("HoaDonMuaHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanCo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanCoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanNo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanNoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanThue")
                        .WithMany()
                        .HasForeignKey("TaiKhoanThueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.VatTuHangHoa", "VatTuHangHoa")
                        .WithMany()
                        .HasForeignKey("VatTuHangHoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDonMuaHang");

                    b.Navigation("TaiKhoanCo");

                    b.Navigation("TaiKhoanNo");

                    b.Navigation("TaiKhoanThue");

                    b.Navigation("VatTuHangHoa");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietLuongNhanVien", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.BangLuongThang", "BangLuongThang")
                        .WithMany("ChiTiets")
                        .HasForeignKey("BangLuongThangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BangLuongThang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChungTuThuChi", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToan")
                        .WithMany()
                        .HasForeignKey("ButToanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ninjaTax.Models.Entities.DoiTuong", "DoiTuong")
                        .WithMany()
                        .HasForeignKey("DoiTuongId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.HoaDonBanHang", "HoaDonBanHang")
                        .WithMany()
                        .HasForeignKey("HoaDonBanHangId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ninjaTax.Models.Entities.HoaDonMuaHang", "HoaDonMuaHang")
                        .WithMany()
                        .HasForeignKey("HoaDonMuaHangId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoanNganHang", "TaiKhoanNganHang")
                        .WithMany()
                        .HasForeignKey("TaiKhoanNganHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ButToan");

                    b.Navigation("DoiTuong");

                    b.Navigation("HoaDonBanHang");

                    b.Navigation("HoaDonMuaHang");

                    b.Navigation("TaiKhoanNganHang");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.DoiTruCongNo", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToan")
                        .WithMany()
                        .HasForeignKey("ButToanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.DoiTuong", "DoiTuong")
                        .WithMany()
                        .HasForeignKey("DoiTuongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.HoaDonBanHang", "HoaDonBanHang")
                        .WithMany()
                        .HasForeignKey("HoaDonBanHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.HoaDonMuaHang", "HoaDonMuaHang")
                        .WithMany()
                        .HasForeignKey("HoaDonMuaHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ButToan");

                    b.Navigation("DoiTuong");

                    b.Navigation("HoaDonBanHang");

                    b.Navigation("HoaDonMuaHang");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.HoaDonBanHang", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToanDoanhThu")
                        .WithMany()
                        .HasForeignKey("ButToanDoanhThuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToanGiaVon")
                        .WithMany()
                        .HasForeignKey("ButToanGiaVonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ninjaTax.Models.Entities.DoiTuong", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ButToanDoanhThu");

                    b.Navigation("ButToanGiaVon");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.HoaDonMuaHang", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToan")
                        .WithMany()
                        .HasForeignKey("ButToanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ninjaTax.Models.Entities.DoiTuong", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ButToan");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.TaiKhoan", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanMe")
                        .WithMany("TaiKhoanCons")
                        .HasForeignKey("TaiKhoanMeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoanMe");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.TaiKhoanNganHang", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanKeToan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanKeToanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoanKeToan");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.TaiSanCoDinh", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanChiPhi")
                        .WithMany()
                        .HasForeignKey("TaiKhoanChiPhiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanKhauHao")
                        .WithMany()
                        .HasForeignKey("TaiKhoanKhauHaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanNguyenGia")
                        .WithMany()
                        .HasForeignKey("TaiKhoanNguyenGiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoanChiPhi");

                    b.Navigation("TaiKhoanKhauHao");

                    b.Navigation("TaiKhoanNguyenGia");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.VatTuHangHoa", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanDoanhThu")
                        .WithMany()
                        .HasForeignKey("TaiKhoanDoanhThuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanGiaVon")
                        .WithMany()
                        .HasForeignKey("TaiKhoanGiaVonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanKho")
                        .WithMany()
                        .HasForeignKey("TaiKhoanKhoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoanDoanhThu");

                    b.Navigation("TaiKhoanGiaVon");

                    b.Navigation("TaiKhoanKho");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.BangChamCongThang", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.BangLuongThang", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ButToan", b =>
                {
                    b.Navigation("ChiTietButToans");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChungTuThuChi", b =>
                {
                    b.Navigation("ChiTietThuChis");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.HoaDonBanHang", b =>
                {
                    b.Navigation("ChiTietBans");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.HoaDonMuaHang", b =>
                {
                    b.Navigation("ChiTietHangs");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("TaiKhoanCons");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.TaiSanCoDinh", b =>
                {
                    b.Navigation("BangTinhKhauHaos");
                });
#pragma warning restore 612, 618
        }
    }
}
