// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ninjaTax.Data;

#nullable disable

namespace ninjaTax.Migrations.Sqlite
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924160114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ninjaTax.Models.Entities.ButToan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DienGiai")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayChungTu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayChungTuGoc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayHachToan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoChungTu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoChungTuGoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongCo")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongNo")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SoChungTu")
                        .IsUnique();

                    b.ToTable("ButToan", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietButToan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ButToanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DienGiai")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DoiTuongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DongSo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("TaiKhoanCoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaiKhoanNoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ButToanId");

                    b.HasIndex("DoiTuongId");

                    b.HasIndex("TaiKhoanCoId");

                    b.HasIndex("TaiKhoanNoId");

                    b.ToTable("ChiTietButToan", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.DoiTuong", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Loai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaDoiTuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiLienHe")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoTaiKhoanNganHang")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDoiTuong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNganHang")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaDoiTuong")
                        .IsUnique();

                    b.ToTable("DoiTuong", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacTaiKhoan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LaTaiKhoanSoCai")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoaiTaiKhoan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TaiKhoanMeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("TinhChat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.HasIndex("TaiKhoanMeId");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ChiTietButToan", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.ButToan", "ButToan")
                        .WithMany("ChiTietButToans")
                        .HasForeignKey("ButToanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.DoiTuong", "DoiTuong")
                        .WithMany()
                        .HasForeignKey("DoiTuongId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanCo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanCoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanNo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanNoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ButToan");

                    b.Navigation("DoiTuong");

                    b.Navigation("TaiKhoanCo");

                    b.Navigation("TaiKhoanNo");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.TaiKhoan", b =>
                {
                    b.HasOne("ninjaTax.Models.Entities.TaiKhoan", "TaiKhoanMe")
                        .WithMany("TaiKhoanCons")
                        .HasForeignKey("TaiKhoanMeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoanMe");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.ButToan", b =>
                {
                    b.Navigation("ChiTietButToans");
                });

            modelBuilder.Entity("ninjaTax.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("TaiKhoanCons");
                });
#pragma warning restore 612, 618
        }
    }
}
